reminders/channels/webpush/urls.py
from django.urls import path
from reminders.channels.webpush.views import add_webpush_device

urlpatterns = [
    path('/',add_webpush_device,name='add_webpush_device')
]

reminders/urls.py
from reminders.views import channel_view,DeviceListView,DeviceDeleteView
from django.urls import path, include
from importlib import import_module
from reminders.channels import REMINDER_CHANNELS

app_name = 'reminders'



# Provider urlpatterns, as separate attribute (for reusability).
channel_urlpatterns = []
for _, channel in REMINDER_CHANNELS.items():
    try:
        ch_mod = import_module(channel.get_package() + '.urls')
    except ImportError:
        continue
    ch_urlpatterns = getattr(ch_mod, 'urlpatterns', None)
    if ch_urlpatterns:
        channel_urlpatterns += ch_urlpatterns



urlpatterns = [
    path('/channels/<str:channel_name>', channel_view, name='channel'),
    path('/channels/<str:channel_name>', include(channel_urlpatterns)),
    path("<int:pk>/remove", DeviceDeleteView.as_view(), name="remove"),
    path('', DeviceListView.as_view(), name='list')
]

study/urls.py
from django.urls import path,include
from study.views import StudyView, SelectWordlistView
from study.api_views import AnswerWordView, OnDueWordView
urlpatterns = [
    path('study/select', SelectWordlistView.as_view(), name='select_wordlist'),
    path('study/<int:wordlist_id>',StudyView.as_view(),name='study'),
    path('api/<int:wordlist_id>/ondue/answer',AnswerWordView.as_view(),name='answer_ondue'),
    path('api/<int:wordlist_id>/ondue',OnDueWordView.as_view(),name='get_ondue'),
]

words_reminder/urls.py
from django.contrib import admin
from django.urls import path,include,reverse_lazy
from django.views.generic import RedirectView,TemplateView
from django.templatetags.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url=reverse_lazy('dashboard'))),
    path('', include('authentication.urls')),
    path('', include('words.urls')),
    path('dashboard', include('dashboard.urls')),
    path('', include('study.urls')),
    path('dictionaries', include('dictionaries.urls')),
    path('reminders', include('reminders.urls',namespace='reminders')), ## FIXME: remove namespace*
    path('firebase-messaging-sw.js', TemplateView.as_view(template_name='webpush/firebase-messaging-sw.js', content_type='application/javascript')),
    path('favicon.ico', RedirectView.as_view(url=static('favicon.ico'))),
    prefix_default_language = False
)

# FIXME: move prefix of apps urls to here

reminders/models.py
from django.db import models
from authentication.models import User
from reminders.channels import REMINDER_CHANNELS
from reminders.reminders import Reminder
import json
from django.utils import timezone


REMINDER_CHANNELS_CHOICES = [(channel.name, channel.title)
                             for channel in REMINDER_CHANNELS.values()]

# Create your models here.
class Device(models.Model):

    user = models.ForeignKey(User, related_name='devices', on_delete=models.CASCADE)
    value = models.TextField(blank=True)
    channel_type = models.CharField(max_length=255, blank=True, choices=REMINDER_CHANNELS_CHOICES)
    last_remind = models.DateTimeField(null=True)
    added_at = models.DateTimeField(default=timezone.now)
    
    def value_json(self):
        return json.loads(self.value)
    
    def remind(self, reminder: Reminder):
        
        kwargs = getattr(reminder, 'to_' + self.channel_type)(user=self.user)

        r = self.channel.remind(self.value_json(), **kwargs)
        
        self.last_remind = timezone.now()
        self.save()
        
        return r
    
    @property
    def channel(self):
        if self.channel_type in REMINDER_CHANNELS:
            return REMINDER_CHANNELS[self.channel_type]
        # FIXME: fix this exception type
        raise AttributeError(f"'{self.channel_type}' channel not registered in reminder channels list")
        
        
            

reminders/forms.py
from django import forms
from reminders.models import Device

class AddDeviceForm(forms.Form):
    pass

reminders/channels/webpush/views.py
from django.views.generic import TemplateView
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from reminders.models import Device
from reminders.channels.webpush.reminder import OneSignalForm
from django.http import HttpResponseBadRequest
import json

class WebPushView(TemplateView):
    template_name = 'reminders/webpush/add_webpush.html'
    
@login_required
def add_webpush_device(request, channel_name):
    form = OneSignalForm(request.POST)
    if form.is_valid():
        device = Device.objects.create(user=request.user, value=json.dumps(form.cleaned_data), channel_type=channel_name)
        return render(request,'reminders/webpush/add_complete.html',{'device': device })
    return HttpResponseBadRequest()
        

channel_view = WebPushView.as_view()

reminders/views.py
from django.shortcuts import render
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from reminders.forms import AddDeviceForm
from reminders.channels import REMINDER_CHANNELS
from reminders.models import Device
from django.views.generic import ListView,DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.http import HttpResponseBadRequest, Http404, HttpResponseNotFound,JsonResponse
from importlib import import_module
from django.urls import reverse_lazy



@login_required
@require_http_methods(['GET'])
def channel_view(request, channel_name):
    if channel_name in REMINDER_CHANNELS:
        channel = REMINDER_CHANNELS[channel_name]
        try:
            module = import_module(channel.get_package() + '.views')
            view = getattr(module,'channel_view')
            if view:
                return view(request)
            
        except ImportError:
            return HttpResponseBadRequest('there is not veiw for this channel')
        
        
class DeviceListView(LoginRequiredMixin, ListView):
    # queryset = Device.objects.all()
    def get_queryset(self):
        return Device.objects.filter(user=self.request.user)
    
    def get_context_data(self, **kwargs):
        kwargs.update({
            'channels' : REMINDER_CHANNELS.values()
        })
        return super().get_context_data(**kwargs)
    

class DeviceDeleteView(LoginRequiredMixin, DeleteView):
    success_url = reverse_lazy('reminders:list')
    def get_queryset(self):
        return Device.objects.filter(user=self.request.user)
    

templates/reminders/device_list.html
{% extends 'base.html' %} 

{% load i18n %}
{% load static %}

{% block body %} 
{% for device in object_list %}


<div class="card shadow mb-3 device" data-id="{{device.id}}">
    <div class="card-header">

        
        {{device.get_channel_type_display}}
        <div style="
                    background: url({% static device.channel.get_icon_path %});
                    width: 20px;
                    height: 20px;
                    background-position: center;
                    background-clip: content-box;
                    background-size: cover;
                    vertical-align: middle;
                " class="mr-2 ml-2 d-inline-block"></div>

        
    
    </div>
     
    <div class="card-body">


        <div class="row mb-3">
            <div class="col-3">
                {% trans "Device Type" %} : {{device.get_channel_type_display}}
            </div>
            <div class="col-5">
                {% trans "Last Remind" %} : {{device.last_remind|default:"فعلان هیچی"}}
            </div>
            <div class="col-4">
                {% trans "Add Date" %} : {{device.added_at|default:""}}
            </div>
        </div>
        <form action="{% url 'reminders:remove' pk=device.id %}" method="post" class="remove-form">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger text-white" value="{% trans "Delete" %}">
        </form>


    </div>
</div>
{% empty %}
<div class="card shadow mb-3"><div class="card-body text-center">
{% trans "There is no added device" %}
</div></div>

{% endfor %} 

<div class="card shadow mb-3">
    <div class="card-header">
    کانال ها
    </div>
    
    <div class="card-body d-flex flex-column justify-content-around align-items-center">
        {% for channel in channels %}
            <a href="{% url 'reminders:channel' channel_name=channel.name %}" class="btn btn-success d-inline-block mb-1">{{channel.title}}</a>
        {% endfor %}

    </div>
</div>

{% endblock body %} 

{% block js %}
<script>
    $('.card.device').each(function(index){
        var deviceId = $(this).data('id');
        if (deviceId == window.localStorage.getItem('deviceId')){
            $(this).children('.card-header').append('({% trans "This device" %})');
        }
    });


</script>
 {% endblock js %}